Update f24

diff --git a/f24 b/f24
--- a/f24
+++ b/f24
@@ -2,17 +2,6 @@
 
 user_agent="Chrome/97"
 root_path=$(pwd)
-
-base_url=$(curl -A $user_agent -s --connect-timeout 5 --head -L https://www.filma24.ch | grep -oP "location: \K.*")
-if [ -z "$base_url" ]
-then
-	echo "Couldn't reach site!"
-	exit 1
-fi
-
-base_url=${base_url:0:-1}
-
-
 newline=$'\n'
 file_size=0
 url_retries=0
@@ -532,6 +521,15 @@ then
 	help_text
 	exit 0
 fi
+
+base_url=$(curl -A $user_agent -s --connect-timeout 5 --head -L https://www.filma24.ch | grep -oP "location: \K.*")
+if [ -z "$base_url" ]
+then
+	echo "Couldn't reach site!"
+	exit 1
+fi
+
+base_url=${base_url:0:-1}
 
 if [ -z "$media_type" ]
 then
